name: Auto Label PRs Based on Title

on:
  pull_request_target:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add Label Based on PR Title
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const patternMap = {
              '!:': 'breaking-change',
              'feat:': 'feature',
              'fix:': 'bug',
              'docs:': 'documentation',
              'style:': 'style',
              'refactor:': 'refactor',
              'test:': 'test',
              'chore:': 'chore'
            };
            const title = context.payload.pull_request.title.toLowerCase();
            const labelsToAdd = Object.entries(patternMap)
              .filter(([key, ]) => title.startsWith(key))
              .map(([, label]) => label);
            
            if (labelsToAdd.length > 0) {
              await github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: labelsToAdd
              });
            }
