name: Check PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check Title
        uses: actions/github-script@v5
        with:
          script: |
            const title = context.payload.pull_request.title;
            const regex = /^(feat|fix|docs|refactor|chore)(\(.\+\))?!?: .+$/; 
            if (!regex.test(title)) {
              core.setFailed('PR title does not follow the convention: ^(feat|fix|docs|refactor|chore)(\(.\+\))?!?: .+$');
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
